### ISSUE TITLE
Fix exercise 6 to use collect 

### ISSUE THREAD

**Issue by ErikSvensson76** [YamenAyoubi/streams_and_lambda#1]
Also solve the problem WITHOUT changing the source. Do that by turning list into a stream and DO NOT use replace all on the list that is what is actually changing the source. Check out the streams lecture

**Comment by YamenAyoubi** [comment]
done

**Comment by ErikSvensson76** [comment]
Fixed and Approved

**Comment by YamenAyoubi** [comment]
Thanks
